name: oculum
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+3


environment:
  sdk: ^3.11.5

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  image_picker: ^1.1.2
  image_cropper: ^9.1.0
  image: ^4.8.0
  shared_preferences: ^2.5.5
  connectivity_plus: 6.1.5
  desktop_drop: ^0.6.0
  path_provider: ^2.1.5
  pdf: ^3.11.3
  supabase_flutter: ^2.12.4
  pasteboard: ^0.5.0
  url_launcher: ^6.3.2
  webview_flutter: ^4.13.1
  webview_windows: ^0.4.0
  web: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/icon/oculum_eye.png
    - assets/oculum/obser.png
    - assets/oculum/sfondo.png
    - assets/oculum/kingi_robot.png
    - assets/oculum/sprites/
    - assets/oculum/sprites/characters/
    - assets/oculum/monsters/
    - assets/oculum/icons/
    - assets/oculum/bosses/
    - assets/oculum_dungeon/generated_sprites/enemies/
    - assets/oculum_dungeon/generated_sprites/equipment/
    - assets/oculum_dungeon/generated_sprites/npc/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/oculum_eye.png"
  adaptive_icon_background: "#07080D"
  adaptive_icon_foreground: "assets/icon/oculum_eye.png"
